#!/usr/bin/env bun

/**
 * Generates client-safe block metadata and dynamic block loaders.
 *
 * The generated catalog intentionally omits executable functions and React
 * components from BlockConfig so UI/search code can inspect block metadata
 * without importing the full blocks registry.
 */

import { readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import type { BlockConfig } from '@/blocks/types'

interface GeneratedBlockEntry {
  type: string
  name: string
  description: string
  category: BlockConfig['category']
  module: string
  iconName?: string
  integrationType?: BlockConfig['integrationType']
  tags?: BlockConfig['tags']
  longDescription?: string
  bestPractices?: string
  docsLink?: string
  bgColor: string
  subBlocks: BlockConfig['subBlocks']
  triggerAllowed?: boolean
  authMode?: BlockConfig['authMode']
  singleInstance?: boolean
  tools: SerializableTools
  inputs: BlockConfig['inputs']
  outputs: BlockConfig['outputs']
  hideFromToolbar?: boolean
  triggers?: BlockConfig['triggers']
}

interface SerializableTools {
  access: string[]
  config?: Record<string, unknown>
  operationToolMap?: Record<string, string>
}

const BLOCKS_DIR = new URL('../blocks/blocks', import.meta.url)
const BLOCKS_DIR_PATH = fileURLToPath(BLOCKS_DIR)
const GENERATED_HEADER = `/**
 * Generated by apps/sim/scripts/generate-block-catalog.ts.
 * Do not edit by hand.
 */
`

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function isBlockConfig(value: unknown): value is BlockConfig {
  return (
    isRecord(value) &&
    typeof value.type === 'string' &&
    typeof value.name === 'string' &&
    typeof value.description === 'string' &&
    typeof value.category === 'string' &&
    typeof value.bgColor === 'string' &&
    Array.isArray(value.subBlocks) &&
    isRecord(value.tools) &&
    isRecord(value.inputs) &&
    isRecord(value.outputs)
  )
}

function toSerializable<T>(value: T): T {
  if (typeof value === 'function') {
    return undefined as T
  }

  if (Array.isArray(value)) {
    return value.map((item) => toSerializable(item)).filter((item) => item !== undefined) as T
  }

  if (!isRecord(value)) {
    return value
  }

  const result: Record<string, unknown> = {}
  for (const [key, nestedValue] of Object.entries(value)) {
    const serializableValue = toSerializable(nestedValue)
    if (serializableValue !== undefined) {
      result[key] = serializableValue
    }
  }
  return result as T
}

function getOperationOptions(block: BlockConfig): Array<{ id?: string }> {
  const operationSubBlock = block.subBlocks.find(
    (subBlock) => subBlock.id === 'operation' && subBlock.type === 'dropdown'
  )
  const options = operationSubBlock?.options
  if (Array.isArray(options)) return options as Array<{ id?: string }>
  if (typeof options !== 'function') return []

  try {
    const resolvedOptions = options()
    return Array.isArray(resolvedOptions) ? (resolvedOptions as Array<{ id?: string }>) : []
  } catch {
    return []
  }
}

function inferToolIdForOperation(block: BlockConfig, operationId: string): string | undefined {
  const access = block.tools?.access ?? []
  if (access.length === 0) return undefined
  if (access.length === 1) return access[0]

  const toolSelector = block.tools?.config?.tool
  if (toolSelector) {
    try {
      const selectedTool = toolSelector({ operation: operationId })
      if (typeof selectedTool === 'string' && selectedTool.length > 0) return selectedTool
    } catch {
      return undefined
    }
  }

  if (access.includes(operationId)) return operationId

  const servicePrefix = `${block.type}_`
  if (operationId.startsWith(servicePrefix)) {
    const withoutPrefix = operationId.slice(servicePrefix.length)
    const prefixedTool = `${block.type}_${withoutPrefix}`
    if (access.includes(prefixedTool)) return prefixedTool
  }

  if (operationId.endsWith(`_${block.type}`)) {
    const withoutSuffix = operationId.slice(0, -block.type.length - 1)
    const prefixedTool = `${block.type}_${withoutSuffix}`
    if (access.includes(prefixedTool)) return prefixedTool
  }

  const prefixedOperation = `${block.type}_${operationId}`
  if (access.includes(prefixedOperation)) return prefixedOperation

  return access.find((toolId) => toolId.startsWith(prefixedOperation))
}

function buildSerializableTools(block: BlockConfig): SerializableTools {
  const tools = toSerializable(block.tools) as SerializableTools
  const operationToolMap = Object.fromEntries(
    getOperationOptions(block)
      .map((option) => {
        if (!option.id) return null
        const toolId = inferToolIdForOperation(block, option.id)
        return toolId ? ([option.id, toolId] as const) : null
      })
      .filter((entry): entry is readonly [string, string] => !!entry)
  )

  if (Object.keys(operationToolMap).length > 0) {
    tools.operationToolMap = operationToolMap
  }

  return tools
}

async function getBlockModuleNames(): Promise<string[]> {
  const entries = await readdir(BLOCKS_DIR, { withFileTypes: true })

  return entries
    .filter(
      (entry) => entry.isFile() && entry.name.endsWith('.ts') && !entry.name.endsWith('.test.ts')
    )
    .map((entry) => entry.name.replace(/\.ts$/, ''))
    .sort((a, b) => a.localeCompare(b))
}

async function loadGeneratedBlockEntries(moduleName: string): Promise<GeneratedBlockEntry[]> {
  let module: Record<string, unknown>
  try {
    module = (await import(`../blocks/blocks/${moduleName}`)) as Record<string, unknown>
  } catch (error) {
    throw new Error(`Failed to load block module "${moduleName}"`, { cause: error })
  }
  const entries: GeneratedBlockEntry[] = []

  for (const exportedValue of Object.values(module)) {
    if (!isBlockConfig(exportedValue)) continue

    entries.push({
      type: exportedValue.type,
      name: exportedValue.name,
      description: exportedValue.description,
      category: exportedValue.category,
      module: moduleName,
      iconName:
        typeof exportedValue.icon === 'function' && exportedValue.icon.name
          ? exportedValue.icon.name
          : undefined,
      integrationType: exportedValue.integrationType,
      tags: toSerializable(exportedValue.tags),
      longDescription: exportedValue.longDescription,
      bestPractices: exportedValue.bestPractices,
      docsLink: exportedValue.docsLink,
      bgColor: exportedValue.bgColor,
      subBlocks: toSerializable(exportedValue.subBlocks),
      triggerAllowed: exportedValue.triggerAllowed,
      authMode: exportedValue.authMode,
      singleInstance: exportedValue.singleInstance,
      tools: buildSerializableTools(exportedValue),
      inputs: toSerializable(exportedValue.inputs),
      outputs: toSerializable(exportedValue.outputs),
      hideFromToolbar: exportedValue.hideFromToolbar,
      triggers: toSerializable(exportedValue.triggers),
    })
  }

  return entries
}

function renderCatalog(entries: GeneratedBlockEntry[]): string {
  return JSON.stringify(Object.fromEntries(entries.map((entry) => [entry.type, entry])))
}

function renderLoaders(moduleNames: string[]): string {
  const entries = moduleNames
    .map((moduleName) => `  ${moduleName}: () => import('@/blocks/blocks/${moduleName}'),`)
    .join('\n')

  return `${GENERATED_HEADER}
export const BLOCK_MODULE_LOADERS = {
${entries}
} satisfies Record<string, () => Promise<Record<string, unknown>>>
`
}

async function main(): Promise<void> {
  const moduleNames = await getBlockModuleNames()
  const entries: GeneratedBlockEntry[] = []
  for (const moduleName of moduleNames) {
    entries.push(...(await loadGeneratedBlockEntries(moduleName)))
  }
  entries.sort((a, b) => a.type.localeCompare(b.type))

  await writeFile(
    new URL('../blocks/catalog.generated.json', import.meta.url),
    renderCatalog(entries)
  )
  await writeFile(
    new URL('../blocks/loaders.generated.ts', import.meta.url),
    renderLoaders(moduleNames)
  )

  process.stdout.write(
    `Generated ${entries.length} block catalog entries from ${moduleNames.length} modules in ${BLOCKS_DIR_PATH}\n`
  )
}

await main()
