#!/usr/bin/env bun

/**
 * Generates client-safe tool metadata and server-only dynamic tool loaders.
 *
 * The generated catalog intentionally omits executable functions from ToolConfig
 * so UI and search code can inspect tool params/outputs without importing the
 * full tools registry.
 */

import { access, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ToolConfig } from '@/tools/types'

interface GeneratedToolEntry {
  id: string
  name: string
  description: string
  version: string
  service: string
  module: string
  params: ToolConfig['params']
  outputs?: ToolConfig['outputs']
  oauth?: ToolConfig['oauth']
  hosting?: ToolConfig['hosting']
}

const TOOLS_DIR = new URL('../tools', import.meta.url)
const TOOLS_DIR_PATH = fileURLToPath(TOOLS_DIR)
const GENERATED_HEADER = `/**
 * Generated by apps/sim/scripts/generate-tool-catalog.ts.
 * Do not edit by hand.
 */
`

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
}

function isToolConfig(value: unknown): value is ToolConfig {
  return (
    isRecord(value) &&
    typeof value.id === 'string' &&
    typeof value.name === 'string' &&
    typeof value.description === 'string' &&
    typeof value.version === 'string' &&
    isRecord(value.params) &&
    isRecord(value.request)
  )
}

function toSerializable<T>(value: T): T {
  if (typeof value === 'function') {
    return undefined as T
  }

  if (Array.isArray(value)) {
    return value.map((item) => toSerializable(item)).filter((item) => item !== undefined) as T
  }

  if (!isRecord(value)) {
    return value
  }

  const result: Record<string, unknown> = {}
  for (const [key, nestedValue] of Object.entries(value)) {
    const serializableValue = toSerializable(nestedValue)
    if (serializableValue !== undefined) {
      result[key] = serializableValue
    }
  }
  return result as T
}

async function getToolModuleNames(): Promise<string[]> {
  const entries = await readdir(TOOLS_DIR, { withFileTypes: true })
  const moduleNames: string[] = []

  for (const entry of entries) {
    if (!entry.isDirectory()) continue

    try {
      const indexPath = join(TOOLS_DIR_PATH, entry.name, 'index.ts')
      await access(indexPath)
      moduleNames.push(entry.name)
    } catch {}
  }

  return moduleNames.sort((a, b) => a.localeCompare(b))
}

async function loadGeneratedToolEntries(moduleName: string): Promise<GeneratedToolEntry[]> {
  const module = (await import(`../tools/${moduleName}`)) as Record<string, unknown>
  const entries: GeneratedToolEntry[] = []

  for (const exportedValue of Object.values(module)) {
    if (!isToolConfig(exportedValue)) continue

    entries.push({
      id: exportedValue.id,
      name: exportedValue.name,
      description: exportedValue.description,
      version: exportedValue.version,
      service: moduleName,
      module: moduleName,
      params: toSerializable(exportedValue.params),
      outputs: toSerializable(exportedValue.outputs),
      oauth: toSerializable(exportedValue.oauth),
      hosting: toSerializable(exportedValue.hosting),
    })
  }

  return entries
}

function renderCatalog(entries: GeneratedToolEntry[]): string {
  return JSON.stringify(Object.fromEntries(entries.map((entry) => [entry.id, entry])))
}

function renderLoaders(moduleNames: string[]): string {
  const entries = moduleNames
    .map((moduleName) => `  ${JSON.stringify(moduleName)}: () => import('@/tools/${moduleName}'),`)
    .join('\n')

  return `${GENERATED_HEADER}
export const TOOL_MODULE_LOADERS = {
${entries}
} satisfies Record<string, () => Promise<Record<string, unknown>>>
`
}

async function main(): Promise<void> {
  const moduleNames = await getToolModuleNames()
  const entries = (await Promise.all(moduleNames.map(loadGeneratedToolEntries)))
    .flat()
    .sort((a, b) => a.id.localeCompare(b.id))

  await writeFile(
    new URL('../tools/catalog.generated.json', import.meta.url),
    renderCatalog(entries)
  )
  await writeFile(
    new URL('../tools/loaders.generated.ts', import.meta.url),
    renderLoaders(moduleNames)
  )

  process.stdout.write(
    `Generated ${entries.length} tool catalog entries from ${moduleNames.length} modules\n`
  )
}

await main()
