/**
 * Generated by apps/sim/scripts/generate-tool-catalog.ts.
 * Do not edit by hand.
 */

export const TOOL_MODULE_LOADERS = {
  file: () => import('@/tools/file'),
  function: () => import('@/tools/function'),
  gmail: () => import('@/tools/gmail'),
  http: () => import('@/tools/http'),
  knowledge: () => import('@/tools/knowledge'),
  llm: () => import('@/tools/llm'),
  logs: () => import('@/tools/logs'),
  memory: () => import('@/tools/memory'),
  notion: () => import('@/tools/notion'),
  parallel: () => import('@/tools/parallel'),
  search: () => import('@/tools/search'),
  slack: () => import('@/tools/slack'),
  table: () => import('@/tools/table'),
  workflow: () => import('@/tools/workflow'),
} satisfies Record<string, () => Promise<Record<string, unknown>>>
