/**
 * Generated by apps/sim/scripts/generate-block-catalog.ts.
 * Do not edit by hand.
 */

export const BLOCK_MODULE_LOADERS = {
  agent: () => import('@/blocks/blocks/agent'),
  api: () => import('@/blocks/blocks/api'),
  chat_trigger: () => import('@/blocks/blocks/chat_trigger'),
  condition: () => import('@/blocks/blocks/condition'),
  file: () => import('@/blocks/blocks/file'),
  function: () => import('@/blocks/blocks/function'),
  generic_webhook: () => import('@/blocks/blocks/generic_webhook'),
  mcp: () => import('@/blocks/blocks/mcp'),
  note: () => import('@/blocks/blocks/note'),
  parallel: () => import('@/blocks/blocks/parallel'),
  response: () => import('@/blocks/blocks/response'),
  router: () => import('@/blocks/blocks/router'),
  search: () => import('@/blocks/blocks/search'),
  start_trigger: () => import('@/blocks/blocks/start_trigger'),
  table: () => import('@/blocks/blocks/table'),
  variables: () => import('@/blocks/blocks/variables'),
  webhook_request: () => import('@/blocks/blocks/webhook_request'),
} satisfies Record<string, () => Promise<Record<string, unknown>>>
